/*----------------------------------------------------------------------------

----------------------------------------------------------------------------*/

#ifndef __CLASS_mySTATISTIC__
#define __CLASS_mySTATISTIC__
#include "Constant_GlobalVariable_MathFunction.h"
class myStatistic
{

    public:
        
		//number of tet changes
        int NumTetChange[MNB];
        //number of BZ changes
        int NumBZChange[MNB];
        //number of quadrant boundary hit events
        int NumCellHit[MNB];
	int phononScatter;
	int impurityScatter;
			//number of phonon real and ficious scat. events
        int ntotp[MNB];          
        //number of phonon real scattering events
        int nreap[MNB];
        //number of phonon self scattering events
        int nslfp[MNB];

        //number of total BH scattering events
        int ntotbh[MNB];
        //number of real BH scattering events
        int nreabh[MNB];
        //number of selfscattering BH scattering events
        int nslfbh[MNB];
        
		//number of II real scattering events
        int nreaii[MNB];

        //number of different phonon scattering events (electrons)
        int nsctype[MNScaEle*NBE][NBE];
        //number of different phonon scattering events (holes)
        int nsctyph[MNScaHole*NBH][NBH];
        //number of different phonon scattering events (oxide electrons)
        int nsctypoe[MNScaOxEle*NBOE][NBOE];
 
        
		//Multiple refresh
        int NumEmptyPSC[NumParType];
		int NumRefresh[NumParType];
		int NumRefreshPSC[MNPSC];//Refresh,
        //energy band dependent before scattering value of charge
        double dtotp[MNB];
public:
		myStatistic();
  void reset();

};

class Contact
{
public:
  int NumContactPlane;
  int BeginI[MNContactPlane];
  int BeginJ[MNContactPlane];
  int BeginK[MNContactPlane];
  int EndI[MNContactPlane];
  int EndJ[MNContactPlane];
  int EndK[MNContactPlane];
  double PhiMS;            
  int NumVappStep;
  double Vapp[MNContactVappStep];
  int TimeSpan[MNContactVappStep];
  
  int CurrentStep;        
  double CurrentVapp;		
  int NumParGen;           //number of particles generated by contact
  double CharGen;          //charge generated by contact
  double EnergyGen;          //charge generated by contact
  int NumParCatch;         //number of particles catched by contact
  double CharCatch;        //charge catched by contact
  double EnergyCatch;        //charge catched by contact

  // 电子/空穴分别统计，便于电流诊断
  int NumEleGen, NumHoleGen;
  int NumEleCatch, NumHoleCatch;
  double CharEleGen, CharHoleGen;
  double CharEleCatch, CharHoleCatch;
public:
  void reset();
};

#endif
